listen_addresses = '*'
max_connections = 20
shared_buffers = 32MB
effective_cache_size = 128MB
work_mem = 2MB
maintenance_work_mem = 16MB
log_min_duration_statement = 100
log_connections = on
log_disconnections = on
